### ISSUE TITLE
Multi-GPU support

### ISSUE THREAD

**Issue by sherjilozair** [karpathy/char-rnn#77] opened 2015-08-07 06:12 UTC
Is Multi-GPU support for this just a matter of using the technique described here https://github.com/torch/cutorch/issues/42 ?

I attempted an implementation: https://github.com/sherjilozair/char-rnn/tree/multigpu, but it doesn't seem to be working correctly.

It seems the `:forward`, `:backward` calls are blocking. What would it take to make them non-blocking?

Any ideas, @karpathy @soumith?

**Comment by ZachzZ** [comment] 2015-08-08 09:52
May you try to update the parameters such as ruu_state in the outside loop? It seems the problem is your inner loop is not completely anynchronous.

**Comment by sherjilozair** [comment] 2015-08-08 10:42
The inner loop is not async, but that is because the `:backward` and `:forward` calls are not async. Something about the LSTM model is making them async. I learnt from @soumith that for non-blocking `:foward`, `backward` calls, the correct way to do multi-gpu would be to use threads. I'll work on that soon.

**Comment by karpathy** [comment] 2015-08-08 11:52
Do we have any concrete example code of non-blocking multi-gpu supported code we could work off of? I have some experience with threading in torch/lua, it can get a bit hairy, especially sharing variables between threads.

**Comment by sherjilozair** [comment] 2015-08-08 11:56
@karpathy,
If the calls to `:forward` and `:backward` were non-blocking, we wouldn't have require threading, except maybe for data loading.

But because they aren't (i.e., they block), we require the threads. An example, albeit toy, for using threads for NN training is here: https://github.com/torch/threads/blob/master/benchmark/threadedtrain.lua

**Comment by karpathy** [comment] 2015-08-08 12:27
Gross. I would be very reluctant to merge something like this to the master since I don't consider multi-gpu to be common enough of a use case to warrant all the ugliness in the code and potential issues that Always come up when threading is involved. I'd support and link to anyone's effort to make their own multi-gpu branch if they wish though.

**Comment by sherjilozair** [comment] 2015-08-08 12:38
If you look at https://github.com/torch/threads/blob/master/test/test-threads.lua, threading in torch is actually quite elegant. It's just the benchmark code which I linked above which is gross. But, I agree that multi-gpu probably does not belong in the master. I opened this issue mainly for discussion and help for implementing it.

**Comment by karpathy** [comment] 2015-09-20 18:42
No current plans for multigpu support, but I encourage people to maintain their own forks with this functionality and I'd be happy to link to it somewhere. Closing issue.

**Closed by karpathy** 2015-09-20 18:42 UTC
